package event

import (
	"encoding/json"
	"fmt"
)

// NormalizeSemantic fills the canonical workflow vocabulary from legacy
// fields and stores it in the event payload. Persisting the small semantic
// envelope keeps old PostgreSQL schemas and old event readers compatible while
// making new projections independent of Turn/Step numbering.
func NormalizeSemantic(input Input) Input {
	var root map[string]json.RawMessage
	if len(input.Payload) > 0 {
		_ = json.Unmarshal(input.Payload, &root)
	}
	if input.PlanNodeID == "" {
		input.PlanNodeID = rawString(root, "plan_node_id", "plan_step_id", "step_id")
	}
	if input.ActionID == "" {
		input.ActionID = rawString(root, "action_id")
	}
	if input.WorkflowID == "" {
		input.WorkflowID = input.RunID
	}
	if input.DecisionCycle == 0 && input.Turn > 0 {
		input.DecisionCycle = input.Turn
	}
	if input.TurnID == "" && input.Turn > 0 {
		// Turn rows are generated by the event projection after TURN_CREATED;
		// this deterministic identity lets all events in the same turn refer to
		// it before that row exists and remains stable across replays.
		input.TurnID = fmt.Sprintf("%s:%d", input.WorkflowID, input.Turn)
	}
	if input.ActionID == "" && input.CallID != "" {
		input.ActionID = input.CallID
	}
	input.Payload = withSemanticEnvelope(input.Payload, input)
	return input
}

func rawString(root map[string]json.RawMessage, keys ...string) string {
	for _, key := range keys {
		var value string
		if raw, ok := root[key]; ok && json.Unmarshal(raw, &value) == nil && value != "" {
			return value
		}
	}
	return ""
}

// SemanticFromPayload reads semantic identifiers emitted by a newer writer.
// Missing fields are intentionally returned as zero values for old events.
func SemanticFromPayload(payload json.RawMessage) (workflowID, planNodeID string, decisionCycle int, actionID string) {
	var envelope struct {
		WorkflowID    string `json:"workflow_id"`
		PlanNodeID    string `json:"plan_node_id"`
		DecisionCycle int    `json:"decision_cycle"`
		ActionID      string `json:"action_id"`
	}
	var root map[string]json.RawMessage
	if len(payload) == 0 || json.Unmarshal(payload, &root) != nil {
		return "", "", 0, ""
	}
	if raw, ok := root["_workflow"]; ok {
		_ = json.Unmarshal(raw, &envelope)
	}
	return envelope.WorkflowID, envelope.PlanNodeID, envelope.DecisionCycle, envelope.ActionID
}

func withSemanticEnvelope(payload json.RawMessage, input Input) json.RawMessage {
	var root map[string]json.RawMessage
	if len(payload) == 0 || json.Unmarshal(payload, &root) != nil {
		return payload
	}
	envelope := map[string]any{"workflow_id": input.WorkflowID}
	if input.SessionID != "" {
		envelope["session_id"] = input.SessionID
	}
	if input.TurnID != "" {
		envelope["turn_id"] = input.TurnID
	}
	if input.CheckpointSeq > 0 {
		envelope["checkpoint_seq"] = input.CheckpointSeq
	}
	if input.ParentEventID != "" {
		envelope["parent_event_id"] = input.ParentEventID
	}
	if input.PlanNodeID != "" {
		envelope["plan_node_id"] = input.PlanNodeID
	}
	if input.DecisionCycle > 0 {
		envelope["decision_cycle"] = input.DecisionCycle
	}
	if input.ActionID != "" {
		envelope["action_id"] = input.ActionID
	}
	encoded, err := json.Marshal(envelope)
	if err != nil {
		return payload
	}
	root["_workflow"] = encoded
	encodedRoot, err := json.Marshal(root)
	if err != nil {
		return payload
	}
	return encodedRoot
}
