experiment_tier: optimize
experiment_name: cpt_opt_native_ddp_base
training_backend: ddp
benchmark_group: cpt_opt_native_ddp_batch8_tf32
tokenized_dataset_path: data/tokenized/cpt/bench
include_num_input_tokens_seen: all

task: continued_pretraining
output_dir: runs/cpt/optimize/native/qwen3_1_7b/ddp_base
logging_dir: runs/cpt/optimize/native/qwen3_1_7b/ddp_base/logs

seed: 42
num_train_epochs: 1
max_steps: 50
save_steps: 1000
eval_steps: 1000
logging_steps: 10
cuda_memory_logging_steps: 10

per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 4

learning_rate: 2.0e-5
weight_decay: 0.1
warmup_ratio: 0.03
lr_scheduler_type: cosine

max_seq_length: 2048
bf16: false
fp16: false
tf32: true

gradient_checkpointing: true
dataloader_num_workers: 2
remove_unused_columns: false
overwrite_output_dir: false
save_total_limit: 1
save_model_artifacts: false
ddp_find_unused_parameters: false
report_to:
  - tensorboard
