DROP INDEX IF EXISTS agent_platform.idx_agent_run_states_workflow_seq;
DROP INDEX IF EXISTS agent_platform.uq_agent_run_states_workflow;
ALTER TABLE agent_platform.agent_run_states DROP CONSTRAINT IF EXISTS fk_agent_run_states_workflow;
ALTER TABLE agent_platform.agent_run_states DROP COLUMN IF EXISTS workflow_id;
DROP INDEX IF EXISTS agent_platform.idx_agent_plan_node_states_ready;
DROP TABLE IF EXISTS agent_platform.agent_plan_node_states;
DROP INDEX IF EXISTS agent_platform.idx_agent_checkpoints_workflow;
ALTER TABLE agent_platform.agent_checkpoints DROP CONSTRAINT IF EXISTS fk_agent_checkpoints_workflow;
ALTER TABLE agent_platform.agent_checkpoints DROP COLUMN IF EXISTS workflow_id;
DROP INDEX IF EXISTS agent_platform.idx_agent_task_plans_workflow_updated;
DROP INDEX IF EXISTS agent_platform.uq_agent_task_plans_workflow;
ALTER TABLE agent_platform.agent_task_plans DROP CONSTRAINT IF EXISTS fk_agent_task_plans_workflow;
ALTER TABLE agent_platform.agent_task_plans DROP COLUMN IF EXISTS workflow_id;
DROP INDEX IF EXISTS agent_platform.idx_agent_runs_workflow;
ALTER TABLE agent_platform.agent_runs DROP CONSTRAINT IF EXISTS fk_agent_runs_workflow;
ALTER TABLE agent_platform.agent_runs DROP COLUMN IF EXISTS workflow_id;
DROP INDEX IF EXISTS agent_platform.idx_agent_workflows_active;
DROP INDEX IF EXISTS agent_platform.idx_agent_workflows_session;
DROP TABLE IF EXISTS agent_platform.agent_workflows;
