task: continued_pretraining
output_dir: runs/cpt/qwen3_1_7b_miniv2_cpt_ddp
logging_dir: runs/cpt/qwen3_1_7b_miniv2_cpt_ddp/logs

seed: 42
num_train_epochs: 1
max_steps: 300
save_steps: 100
eval_steps: 100
logging_steps: 10
cuda_memory_logging_steps: 10

per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 8

learning_rate: 2.0e-5
weight_decay: 0.1
warmup_ratio: 0.03
lr_scheduler_type: cosine

max_seq_length: 2048
bf16: false
fp16: false
tf32: true

gradient_checkpointing: true
dataloader_num_workers: 4
remove_unused_columns: false
overwrite_output_dir: false
save_total_limit: 3
ddp_find_unused_parameters: false
report_to:
  - tensorboard
